export { default as Home } from './home/Home';
export { default as HeatMap } from './heatmap/HeatMap';
export { default as WordCloud } from './wordcloud/WordCloud';
export { default as BarCharts } from './barcharts/BarCharts';
export { default as Universities } from './universities/Universities';
export { default as Keywords} from './keywords/Keywords';
export { default as Signin } from './signin/Signin';
export { default as Register } from './register/Register';
export { default as Error } from './error/Error';
export { default as Test } from './test/Test';